import React from "react"
import Hero1 from "../images/hero1.png"
import Hero2 from "../images/hero2.png"
import Hero3 from "../images/hero3.png"

const EarnMoney = () => {
  return (
    <section className="py-10 w-9/12 md:w-8/12 mx-auto">
      <div>
        <img
          src="https://framerusercontent.com/images/7aKKvEZCSVRFsDSyHuluqzNp1RQ.png?scale-down-to=512"
          alt=""
          width={"200px"}
          className="mx-auto mb-10"
        />
        <h1 className="text-4xl lg:text-6xl font-bold">
          Earn Money.
          <span className="text-yellow-300 block sm:inline">
            {" "}
            The Easy Way.
          </span>
        </h1>
        <p className="text-md md:text-xl lg:text-2xl mt-3">
          Best-in-class referral and rebate program. Refer a friend and you
          would get 70%* of fee generated by your friend and your friend would
          get upto 20%* of rebate on fee.
        </p>
      </div>
      <div className="mt-20 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 justify-center font-bold">
        <div className="p-5 bg-gray-600 mx-auto flex md:block gap-10 items-center rounded-lg max-w-[300px]">
          <img src={Hero1} alt="" width={"60px"} className="mx-auto" />
          <h1 className="text-3xl">Daily Payouts</h1>
        </div>
        <div className="p-5 bg-gray-600 mx-auto flex md:block gap-10 items-center rounded-lg max-w-[300px]">
          <img src={Hero2} alt="" width={"100px"} className="mx-auto" />
          <h1 className="text-3xl">Unlimited Invites</h1>
        </div>
        <div className="p-5 bg-gray-600 mx-auto flex md:block gap-10 items-center rounded-lg max-w-[300px]">
          <img src={Hero3} alt="" width={"100px"} className="mx-auto" />
          <h1 className="text-3xl">Trade & Earn</h1>
        </div>
      </div>
      <button
        type="button"
        className="bg-gradient-to-r from-yellow-300 to-green-400 w-64 h-12 rounded-lg text-black font-bold text-xl mt-20 mb-32"
      >
        START EARNING NOW
      </button>
    </section>
  )
}

export default EarnMoney
